apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: newsman
          artifact-id: cf8a155f-f595-4cd3-bee6-d4f7fd8b98cc
          target-environment: QA